### ISSUE TITLE
Add Harmony Python package version to /info/version endpoint

### ISSUE THREAD

**Issue by woodthom2** [harmonydata/harmonyapi#3]
we have an /info/version endpoint in the API

https://api.harmonydata.ac.uk/docs#/Info/show_version_info_version_get

![image](https://github.com/harmonydata/harmonyapi/assets/15210965/b558348d-cced-4746-a1ee-a16ff5b08605)

However this is showing the commit ID only (taken from an environment variable at the time the Docker container is built)

We should also include the version of Harmony Python package in the return value, for example as below:

```
{
  "version_id": "20240122115533_2aa3327"
  "harmony_version": "0.5.0"
}
```

When this is completed we need to display the version in the front end - see related front end issue: https://github.com/harmonydata/app/issues/12

**Comment by ronnyTodgers** [comment]
Makes a lot of sense!

**Comment by woodthom2** [comment]
Fixed in repo and redeployed today https://api.harmonydata.ac.uk/docs#/Info

**Comment by woodthom2** [comment]
fixed
